apiVersion: "v1"
kind: Pod
metadata:
   name: web
   labels:
     name: web
     app: demo
spec:
   containers:
      - 
        env:
           - name: REDIS_HOST
             value: "redis-svc.default.svc.cluster.local"
        name: web
        image: sagar23/webapp-kube:latest
        ports:
         - containerPort: 5000
           name: http
           protocol: TCP 
