apiVersion: "v1"
kind: Pod
metadata:
   name: web
   labels:
     name: web
     app: demo
spec:
   containers:
      - name: web
        image: sagar23/webapp-kube
        ports:
         - containerPort: 5000
           name: http
           protocol: TCP 
